name: Build slackhq/vitess

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    name: Build Vitess
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v4
      with:
        repository: slackhq/vitess
        ref: slack-19.0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: false

    - name: Setup github.com/slackhq/vitess-additions access token
      run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/

    - name: Get dependencies
      timeout-minutes: 15
      run: go mod download
